// Generated by Framer (861d57e)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "6p5i5q"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-BnlWR", title: siteMetadata(params, activeLocale).title || "Page", viewport: "width=1200"}
}

export const metadataVersion = 1