// Generated by Framer (629c622)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "qqtw6e"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-JP1uL", title: siteMetadata(params, activeLocale).title || "Page", viewport: "width=1200"}
}

export const metadataVersion = 1