// Generated by Framer (018ad06)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-kXkhhmZm_", breakpoints: [{hash: "nl9ovh", mediaQuery: "(min-width: 1440px)"}, {hash: "clc9i4", mediaQuery: "(min-width: 1200px) and (max-width: 1439px)"}, {hash: "11p5fbc", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "s7nwkl", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, framerSearch: {index: false}, robots: "noindex", serializationId: "framer-gPrz5", title: siteMetadata(params, activeLocale).title || "404", viewport: "width=device-width"}
}

export const metadataVersion = 1