// Generated by Framer (629c622)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "7jx7er", mediaQuery: "(min-width: 1440px)"}, {hash: "jo6p6w", mediaQuery: "(min-width: 1400px) and (max-width: 1439px)"}, {hash: "hv17gr", mediaQuery: "(min-width: 1200px) and (max-width: 1399px)"}, {hash: "aui0bs", mediaQuery: "(min-width: 1200px) and (max-width: 1199px)"}, {hash: "gecupg", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1wco5o3", mediaQuery: "(max-width: 809px)"}], description: "Pricing And Plans Overview For THEEACE Ag. Clear Presentation Of Available Options.", elements: {}, robots: "max-image-preview:large", serializationId: "framer-rqwlN", title: "THEEACE Ag Pricing And Plans", viewport: "width=device-width"}
}

export const metadataVersion = 1