// Generated by Framer (b8d5a97)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1rxml1l", mediaQuery: "(min-width: 1200px)"}, {hash: "1p2h8yt", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "rt6epj", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {aNAkAg2cv: "pricing-1", O2UmFEWea: "pricing"}, robots: "max-image-preview:large", serializationId: "framer-rDXE4", title: siteMetadata(params, activeLocale).title || "Pricing And Plans", viewport: "width=device-width"}
}

export const metadataVersion = 1