// Generated by Framer (114679e)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "ff96i4", mediaQuery: "(min-width: 1200px)"}, {hash: "1ww5ua1", mediaQuery: "(min-width: 1200px) and (max-width: 1199px)"}, {hash: "1y9htfb", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1kf6lc9", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-0fClX", title: siteMetadata(params, activeLocale).title || "Thankyou", viewport: "width=device-width"}
}

export const metadataVersion = 1