// Generated by Framer (14b65b1)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1nw7qtb", mediaQuery: "(min-width: 1440px)"}, {hash: "1n804fs", mediaQuery: "(min-width: 1200px) and (max-width: 1439.98px)"}, {hash: "si9v1y", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "a7w9nn", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {gVg3BF4K5: "pricing"}, framerSearch: {index: true}, robots: "noindex", serializationId: "framer-rlOh8", title: siteMetadata(params, activeLocale).title || "Configuration", viewport: "width=device-width"}
}

export const metadataVersion = 1