// Generated by Framer (662ecd5)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "464bs4", mediaQuery: "(min-width: 1440px)"}, {hash: "krpmc9", mediaQuery: "(min-width: 1200px) and (max-width: 1439px)"}, {hash: "7ouyx4", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "9jb1sd", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {nwLc2RAPY: "pricing", z6aH3U3hm: "pricing-1"}, robots: "max-image-preview:large", serializationId: "framer-rJzLR", title: siteMetadata(params, activeLocale).title || "Pricing", viewport: "width=device-width"}
}

export const metadataVersion = 1